# Generated by Django 4.1.13 on 2025-07-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='accept_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
