# Generated by Django 4.1.13 on 2025-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_complaint_accept_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_jantadarbar',
            field=models.BooleanField(default=False),
        ),
    ]
