# Generated by Django 4.1.13 on 2025-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_user_is_jantadarbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_jantadarbar_complain',
            field=models.BooleanField(default=False),
        ),
    ]
