# Generated by Django 4.1.13 on 2025-07-25 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_complaint_is_jantadarbar_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintimage',
            name='image_type',
            field=models.CharField(choices=[('complaint', 'Complaint Image'), ('resolution', 'Resolution Image')], default='complaint', max_length=20),
        ),
        migrations.AddField(
            model_name='complaintimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
