# Generated by Django 4.1.13 on 2025-08-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_complaintimage_image_type_complaintimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintaction',
            name='action_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintaction',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_from', to='rest_api.department'),
        ),
        migrations.AlterField(
            model_name='complaintaction',
            name='action',
            field=models.CharField(choices=[('forwarded', 'Forwarded'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('accepted', 'Accepted'), ('disposed', 'Disposed'), ('admin_review', 'Admin Review')], max_length=50),
        ),
    ]
